In [9]:
import pandas as pd

base = pd.read_csv("https://raw.githubusercontent.com/MSR1805200/nivelamento_2026_2/refs/heads/master/dados/cliente.csv")

base

    id_cliente      nome  idade estado tipo_cliente
0            1       Ana     28     PE         Novo
1            2    Carlos     35     PB   Recorrente
2            3   Beatriz     22     PB         Novo
3            4    Daniel     41     PE   Recorrente
4            5       Ana     33     RN         Novo
5            6    Carlos     29     PE   Recorrente
6            7  Fernanda     24     PB         Novo
7            8    Daniel     38     RN   Recorrente
8            9   Beatriz     26     PE         Novo
9           10  Fernanda     31     PB   Recorrente
10          11     Lucas     45     RN         Novo
11          12    Marina     27     PE   Recorrente

In [10]:
base.shape

(12, 5)

In [11]:
base.head()

   id_cliente     nome  idade estado tipo_cliente
0           1      Ana     28     PE         Novo
1           2   Carlos     35     PB   Recorrente
2           3  Beatriz     22     PB         Novo
3           4   Daniel     41     PE   Recorrente
4           5      Ana     33     RN         Novo

In [12]:
base.columns

Index(['id_cliente', 'nome', 'idade', 'estado', 'tipo_cliente'], dtype='object')

In [13]:
base["id_cliente"]

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
Name: id_cliente, dtype: int64

In [14]:
base[["id_cliente","nome"]]

    id_cliente      nome
0            1       Ana
1            2    Carlos
2            3   Beatriz
3            4    Daniel
4            5       Ana
5            6    Carlos
6            7  Fernanda
7            8    Daniel
8            9   Beatriz
9           10  Fernanda
10          11     Lucas
11          12    Marina

In [15]:
base

    id_cliente      nome  idade estado tipo_cliente
0            1       Ana     28     PE         Novo
1            2    Carlos     35     PB   Recorrente
2            3   Beatriz     22     PB         Novo
3            4    Daniel     41     PE   Recorrente
4            5       Ana     33     RN         Novo
5            6    Carlos     29     PE   Recorrente
6            7  Fernanda     24     PB         Novo
7            8    Daniel     38     RN   Recorrente
8            9   Beatriz     26     PE         Novo
9           10  Fernanda     31     PB   Recorrente
10          11     Lucas     45     RN         Novo
11          12    Marina     27     PE   Recorrente

In [18]:
#base[ base["estado"] == "PE" ]

base.loc[ base["estado"] == "PE", ["tipo_cliente"] ]

   tipo_cliente
0          Novo
3    Recorrente
5    Recorrente
8          Novo
11   Recorrente

In [19]:
# & - E
# | - OU
# == - igual a


base.loc[  (base["estado"] == "PE")  & (base["idade"] > 28) ]

   id_cliente    nome  idade estado tipo_cliente
3           4  Daniel     41     PE   Recorrente
5           6  Carlos     29     PE   Recorrente

In [21]:
base_estado_idade = base.loc[  (base["estado"] == "PE")  & (base["idade"] > 28) ]

base_estado_idade

   id_cliente    nome  idade estado tipo_cliente
3           4  Daniel     41     PE   Recorrente
5           6  Carlos     29     PE   Recorrente

In [22]:
base_id_nome = base[["id_cliente","nome"]]
base_id_nome

    id_cliente      nome
0            1       Ana
1            2    Carlos
2            3   Beatriz
3            4    Daniel
4            5       Ana
5            6    Carlos
6            7  Fernanda
7            8    Daniel
8            9   Beatriz
9           10  Fernanda
10          11     Lucas
11          12    Marina

In [24]:
base["idade"]

0     28
1     35
2     22
3     41
4     33
5     29
6     24
7     38
8     26
9     31
10    45
11    27
Name: idade, dtype: int64

In [26]:
idade_mais_10 =  base["idade"] + 10
idade_mais_10

0     38
1     45
2     32
3     51
4     43
5     39
6     34
7     48
8     36
9     41
10    55
11    37
Name: idade, dtype: int64

In [27]:
base["idade_mais_10"] = idade_mais_10

In [28]:
base

    id_cliente      nome  idade estado tipo_cliente  idade_mais_10
0            1       Ana     28     PE         Novo             38
1            2    Carlos     35     PB   Recorrente             45
2            3   Beatriz     22     PB         Novo             32
3            4    Daniel     41     PE   Recorrente             51
4            5       Ana     33     RN         Novo             43
5            6    Carlos     29     PE   Recorrente             39
6            7  Fernanda     24     PB         Novo             34
7            8    Daniel     38     RN   Recorrente             48
8            9   Beatriz     26     PE         Novo             36
9           10  Fernanda     31     PB   Recorrente             41
10          11     Lucas     45     RN         Novo             55
11          12    Marina     27     PE   Recorrente             37

In [29]:
base.groupby("estado").size()

estado
PB    4
PE    5
RN    3
dtype: int64

In [31]:
base.groupby("estado")["idade"].mean()

estado
PB    28.000000
PE    30.200000
RN    38.666667
Name: idade, dtype: float64

In [34]:
base.groupby("estado").agg({
    "idade" : ["mean", "std", "median","size"]
})

            idade
             mean       std median size
estado
PB      28.000000  6.055301   27.5    4
PE      30.200000  6.140033   28.0    5
RN      38.666667  6.027714   38.0    3