# Exercícios — Introdução à Manipulação de Dados com Pandas

[![Abrir no Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/MSR1805200/nivelamento_2026_2/blob/master/exercicios_dia_1_gabarito.ipynb).

Utilize a base de dados `vendas.csv` para responder aos exercícios abaixo.

---

## Parte 1 — Conhecendo os dados

### Exercício 1 — Importando a base

Importe a biblioteca Pandas e leia o arquivo `vendas.csv`.

O `DataFrame` criado deve se chamar `df`.

In [ ]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/MSR1805200/nivelamento_2026_2/refs/heads/master/dados/vendas.csv")


---

### Exercício 2 — Visualizando os dados

Utilize comandos do Pandas para:

a) Mostrar todo o `DataFrame`.

b) Mostrar apenas as 5 primeiras linhas.
---

In [ ]:
#a
df

,id_venda,cliente,cidade,produto,categoria,quantidade,preco,vendedor
0,1,Ana,Recife,Notebook,Eletrônicos,1,3500,João
1,2,Carlos,Olinda,Mouse,Eletrônicos,2,80,Maria
2,3,Beatriz,Recife,Teclado,Eletrônicos,1,150,João
3,4,Daniel,Jaboatão,Cadeira,Móveis,1,700,Pedro
4,5,Ana,Recife,Mouse,Eletrônicos,1,80,Maria
5,6,Carlos,Olinda,Cadeira,Móveis,2,700,Pedro
6,7,Fernanda,Recife,Notebook,Eletrônicos,1,3500,João
7,8,Daniel,Jaboatão,Teclado,Eletrônicos,2,150,Maria
8,9,Beatriz,Recife,Cadeira,Móveis,1,700,Pedro
9,10,Fernanda,Olinda,Mouse,Eletrônicos,3,80,Maria

In [ ]:
#b
df.head()

,id_venda,cliente,cidade,produto,categoria,quantidade,preco,vendedor
0,1,Ana,Recife,Notebook,Eletrônicos,1,3500,João
1,2,Carlos,Olinda,Mouse,Eletrônicos,2,80,Maria
2,3,Beatriz,Recife,Teclado,Eletrônicos,1,150,João
3,4,Daniel,Jaboatão,Cadeira,Móveis,1,700,Pedro
4,5,Ana,Recife,Mouse,Eletrônicos,1,80,Maria


### Exercício 3 — Conhecendo a estrutura

Utilize comandos do Pandas para descobrir:

a) Quantas linhas existem na base?

b) Quantas colunas existem?

c) Quais são os nomes das colunas?

In [ ]:
#a e b
df.shape

(10, 8)

In [ ]:
#c
df.columns

Index(['id_venda', 'cliente', 'cidade', 'produto', 'categoria', 'quantidade',
       'preco', 'vendedor'],
      dtype='object')

---

## Parte 2 — Selecionando colunas

### Exercício 4 — Selecionando uma coluna

Mostre somente a coluna `produto`.

Depois, faça o mesmo para:

a) `cliente`

b) `cidade`

c) `quantidade`

d) `vendedor`

---

In [ ]:
df["produto"]

0    Notebook
1       Mouse
2     Teclado
3     Cadeira
4       Mouse
5     Cadeira
6    Notebook
7     Teclado
8     Cadeira
9       Mouse
Name: produto, dtype: object

In [ ]:
#a
df["cliente"]

0         Ana
1      Carlos
2     Beatriz
3      Daniel
4         Ana
5      Carlos
6    Fernanda
7      Daniel
8     Beatriz
9    Fernanda
Name: cliente, dtype: object

In [ ]:
#b
df["cidade"]

0      Recife
1      Olinda
2      Recife
3    Jaboatão
4      Recife
5      Olinda
6      Recife
7    Jaboatão
8      Recife
9      Olinda
Name: cidade, dtype: object

In [ ]:
#c
df["quantidade"]

0    1
1    2
2    1
3    1
4    1
5    2
6    1
7    2
8    1
9    3
Name: quantidade, dtype: int64

In [ ]:
#d
df["vendedor"]

0     João
1    Maria
2     João
3    Pedro
4    Maria
5    Pedro
6     João
7    Maria
8    Pedro
9    Maria
Name: vendedor, dtype: object

### Exercício 5 — Selecionando várias colunas

Mostre somente as seguintes informações:

* `cliente`
* `produto`
* `quantidade`
* `preco`

---

In [ ]:
df[["cliente","produto","quantidade","preco"]]

    cliente   produto  quantidade  preco
0       Ana  Notebook           1   3500
1    Carlos     Mouse           2     80
2   Beatriz   Teclado           1    150
3    Daniel   Cadeira           1    700
4       Ana     Mouse           1     80
5    Carlos   Cadeira           2    700
6  Fernanda  Notebook           1   3500
7    Daniel   Teclado           2    150
8   Beatriz   Cadeira           1    700
9  Fernanda     Mouse           3     80


## Parte 3 — Filtrando dados

### Exercício 6 — Vendas em Recife

Mostre somente as vendas realizadas na cidade de **Recife**.

Quantas vendas foram realizadas em Recife?

In [ ]:
df

,id_venda,cliente,cidade,produto,categoria,quantidade,preco,vendedor
0,1,Ana,Recife,Notebook,Eletrônicos,1,3500,João
1,2,Carlos,Olinda,Mouse,Eletrônicos,2,80,Maria
2,3,Beatriz,Recife,Teclado,Eletrônicos,1,150,João
3,4,Daniel,Jaboatão,Cadeira,Móveis,1,700,Pedro
4,5,Ana,Recife,Mouse,Eletrônicos,1,80,Maria
5,6,Carlos,Olinda,Cadeira,Móveis,2,700,Pedro
6,7,Fernanda,Recife,Notebook,Eletrônicos,1,3500,João
7,8,Daniel,Jaboatão,Teclado,Eletrônicos,2,150,Maria
8,9,Beatriz,Recife,Cadeira,Móveis,1,700,Pedro
9,10,Fernanda,Olinda,Mouse,Eletrônicos,3,80,Maria

In [ ]:
df.loc[df['cidade']=="Recife"]

,id_venda,cliente,cidade,produto,categoria,quantidade,preco,vendedor
0,1,Ana,Recife,Notebook,Eletrônicos,1,3500,João
2,3,Beatriz,Recife,Teclado,Eletrônicos,1,150,João
4,5,Ana,Recife,Mouse,Eletrônicos,1,80,Maria
6,7,Fernanda,Recife,Notebook,Eletrônicos,1,3500,João
8,9,Beatriz,Recife,Cadeira,Móveis,1,700,Pedro

---

### Exercício 7 — Vendas de Notebook

Mostre somente as vendas cujo produto seja **Notebook**.

Quantas vendas de Notebook existem na base?

---

In [ ]:
notebook = df.loc[df['produto']=="Notebook"]
notebook.shape # como cada linha tem o produto igual a 1 então para descorbir quantas vendas teve, basta utilizar o comando shape que irá contar a quantidade de linhas

# comando alternativo: ele vai te dar o mesmo resultado
#notebook["produto"].sum()

(2, 8)


### Exercício 8 — Quantidade vendida

Mostre somente as vendas em que a quantidade de produtos vendidos seja **maior que 1**.

Depois, faça:

a) Quantidade maior ou igual a 2.

b) Quantidade igual a 1.

c) Quantidade diferente de 1.

---

In [ ]:
df.loc[df["quantidade"] > 1]

,id_venda,cliente,cidade,produto,categoria,quantidade,preco,vendedor
1,2,Carlos,Olinda,Mouse,Eletrônicos,2,80,Maria
5,6,Carlos,Olinda,Cadeira,Móveis,2,700,Pedro
7,8,Daniel,Jaboatão,Teclado,Eletrônicos,2,150,Maria
9,10,Fernanda,Olinda,Mouse,Eletrônicos,3,80,Maria

In [ ]:
#a
df.loc[df["quantidade"] >= 2]

,id_venda,cliente,cidade,produto,categoria,quantidade,preco,vendedor
1,2,Carlos,Olinda,Mouse,Eletrônicos,2,80,Maria
5,6,Carlos,Olinda,Cadeira,Móveis,2,700,Pedro
7,8,Daniel,Jaboatão,Teclado,Eletrônicos,2,150,Maria
9,10,Fernanda,Olinda,Mouse,Eletrônicos,3,80,Maria

In [ ]:
#c
df.loc[df["quantidade"] != 1]

,id_venda,cliente,cidade,produto,categoria,quantidade,preco,vendedor
1,2,Carlos,Olinda,Mouse,Eletrônicos,2,80,Maria
5,6,Carlos,Olinda,Cadeira,Móveis,2,700,Pedro
7,8,Daniel,Jaboatão,Teclado,Eletrônicos,2,150,Maria
9,10,Fernanda,Olinda,Mouse,Eletrônicos,3,80,Maria


### Exercício 9 — Filtros com números

Mostre somente as vendas em que o preço do produto seja **maior que 500**.

Quais produtos possuem preço maior que 500?

---

In [ ]:
df.loc[df["preco"] > 500]

,id_venda,cliente,cidade,produto,categoria,quantidade,preco,vendedor
0,1,Ana,Recife,Notebook,Eletrônicos,1,3500,João
3,4,Daniel,Jaboatão,Cadeira,Móveis,1,700,Pedro
5,6,Carlos,Olinda,Cadeira,Móveis,2,700,Pedro
6,7,Fernanda,Recife,Notebook,Eletrônicos,1,3500,João
8,9,Beatriz,Recife,Cadeira,Móveis,1,700,Pedro

### Exercício 10 — Filtros com duas condições

Mostre as vendas que aconteceram em **Recife** e possuem **quantidade maior que 1**.

---

In [ ]:
df.loc[(df["cidade"] == "Recife") & (df["quantidade"] > 1)]

Empty DataFrame
Columns: [id_venda, cliente, cidade, produto, categoria, quantidade, preco, vendedor]
Index: []

### Exercício 11 — Filtros com duas condições

Mostre as vendas que possuem o produto **Mouse** ou **Teclado**.

---

In [ ]:
df.loc[(df["produto"] == "Mouse") | (df["produto"] == "Teclado")]

,id_venda,cliente,cidade,produto,categoria,quantidade,preco,vendedor
1,2,Carlos,Olinda,Mouse,Eletrônicos,2,80,Maria
2,3,Beatriz,Recife,Teclado,Eletrônicos,1,150,João
4,5,Ana,Recife,Mouse,Eletrônicos,1,80,Maria
7,8,Daniel,Jaboatão,Teclado,Eletrônicos,2,150,Maria
9,10,Fernanda,Olinda,Mouse,Eletrônicos,3,80,Maria


## Parte 4 — Agrupando dados

### Exercício 12 — Quantidade de vendas por vendedor

Agrupe os dados por `vendedor` e descubra quantas vendas cada vendedor realizou.

---

In [ ]:
df.groupby('vendedor').size()

vendedor
João     3
Maria    4
Pedro    3
dtype: int64


### Exercício 13 — Quantidade total de produtos por vendedor

Agrupe os dados por `vendedor` e descubra quantos produtos cada vendedor vendeu no total.

---

In [ ]:
df.groupby('vendedor')["quantidade"].sum()

vendedor
João     3
Maria    8
Pedro    4
Name: quantidade, dtype: int64


### Exercício 14 — Vendas por cidade

Agrupe os dados por `cidade` e descubra quantas vendas foram realizadas em cada cidade.

---

In [ ]:
df.groupby('cidade').size()

cidade
Jaboatão    2
Olinda      3
Recife      5
dtype: int64


### Exercício 15 — Quantidade de produtos por cidade

Agrupe os dados por `cidade` e descubra quantos produtos foram vendidos em cada cidade.

Compare o resultado com o exercício anterior.

Por que os resultados são diferentes?

---

In [ ]:
df.groupby('cidade')['quantidade'].sum()

cidade
Jaboatão    3
Olinda      7
Recife      5
Name: quantidade, dtype: int64


### Exercício 16 — Quantidade vendida por produto

Agrupe os dados por `produto` e descubra qual foi a quantidade total vendida de cada produto.

In [ ]:
df.groupby("produto")["quantidade"].sum()

produto
Cadeira     4
Mouse       6
Notebook    2
Teclado     3
Name: quantidade, dtype: int64

---

### Exercício 17 — Quantidade vendida por categoria

Agrupe os dados por `categoria` e descubra quantos produtos foram vendidos em cada categoria.

In [ ]:
df.groupby("categoria")["quantidade"].sum()

categoria
Eletrônicos    11
Móveis          4
Name: quantidade, dtype: int64

---

## Parte 5 — Desafios

### Exercício 18 — Quem vendeu mais?

Descubra qual vendedor vendeu a maior quantidade de produtos.

---

In [ ]:
df.groupby("vendedor")["quantidade"].sum()[1:2]

# alternativa 1
#df.groupby("vendedor")["quantidade"].sum().sort_values(ascending = False)[0:1]

# alternativa 2
#df.groupby("vendedor")["quantidade"].sum().nlargest(1)

vendedor
Maria    8
Name: quantidade, dtype: int64

### Exercício 19 — Qual cidade vendeu mais?

Descubra qual cidade teve a maior quantidade de produtos vendidos.

In [ ]:
df.groupby("cidade")["quantidade"].sum()[1:2]

cidade
Olinda    7
Name: quantidade, dtype: int64

---

### Exercício 20 — Analisando Recife

Considere somente as vendas realizadas em **Recife**.

Depois, descubra qual produto teve a maior quantidade vendida em Recife.

---

In [ ]:
base_recife = df.loc[ df["cidade"] == "Recife"]

base_recife.groupby("produto")["quantidade"].sum()[2:3]

produto
Notebook    2
Name: quantidade, dtype: int64


## Desafio final — Mini análise de vendas

### Exercício 21

Utilizando a base completa, responda:

a) Qual é o produto mais vendido em quantidade?

b) Qual vendedor vendeu mais produtos?

c) Qual cidade realizou mais vendas?

d) Qual categoria possui mais produtos vendidos?

e) Qual produto possui o maior preço?

f) Quais vendas possuem quantidade maior que 1?

g) Quantas vendas foram realizadas por cada vendedor?

h) Quantos produtos foram vendidos no total?

In [ ]:
#a
df.groupby("produto")["quantidade"].sum()[1:2]

produto
Mouse    6
Name: quantidade, dtype: int64

In [ ]:
#b
df.groupby("vendedor")["quantidade"].sum()[1:2]

vendedor
Maria    8
Name: quantidade, dtype: int64

In [ ]:
#c
df.groupby("cidade").size()[1:2]

cidade
Olinda    3
dtype: int64

In [ ]:
#d
df.groupby("categoria")["quantidade"].sum()[0:1]

categoria
Eletrônicos    11
Name: quantidade, dtype: int64

In [ ]:
#e
df.groupby("produto")["preco"].max()[2:3]

produto
Notebook    3500
Name: preco, dtype: int64

In [ ]:
#f
df.loc[df["quantidade"] > 1]

,id_venda,cliente,cidade,produto,categoria,quantidade,preco,vendedor
1,2,Carlos,Olinda,Mouse,Eletrônicos,2,80,Maria
5,6,Carlos,Olinda,Cadeira,Móveis,2,700,Pedro
7,8,Daniel,Jaboatão,Teclado,Eletrônicos,2,150,Maria
9,10,Fernanda,Olinda,Mouse,Eletrônicos,3,80,Maria

In [ ]:
#g
df.groupby("vendedor").size()

vendedor
João     3
Maria    4
Pedro    3
dtype: int64

In [ ]:
#h
df["quantidade"].sum()

np.int64(15)